# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Georgi Stefanov
email: geosteffanov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello and welcome to my personal blog! My name is Georgi Stefanov
  and I am a student of Computer Science(and Mathematics). Here you will
  find general information about me and my work. I hope you enjoy your stay here!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://geosteffanov.github.io/" # the base hostname & protocol for your site
github_username:  geosteffanov
# Build settings
markdown: kramdown
